query GetIncidencias($hotel_id: ID!, $fecha_operacion: DateSearchInput) {
    incidencias(hotel_id: $hotel_id, fecha_operacion: $fecha_operacion) {
        incidencia_id
        detalle
        habitacion_id
        folio
        fecha_registro
        fecha_cierre
        colaborador_id_reporta
        estado
        huesped
        matricula
        tipo_incidencia
        colaborador_reporta {
            nombre
            apellido_paterno
            apellido_materno
            puesto {
                nombre
            }
        }
        colaborador_id_cierra
        colaborador_cierra {
            nombre
            apellido_paterno
            apellido_materno
        }
        area
        severidad
        turno_id
        turno {
            nombre
        }
        habitacion {
            habitacion_id
            numero_habitacion
            tipo_habitacion_id
            tipo_habitacion {
                tipo_habitacion_id
                nombre
            }
        }
        imagenes {
            imagen
        }
    }
}

query ObtenerBandejaIncidencias($usuarioId: [String!]!, $hotelId: [String!]) {
    obtener_bandeja_incidencias(usuario_id: $usuarioId, hotel_id: $hotelId) {
        bandeja_notificaciones_id
        hotel_id
        leido
        incidencia_id
        incidencia {
            incidencia_id
            detalle
            habitacion_id
            tipo_incidencia
        }
    }
}

mutation marcarComoLeida($bandejaNotificacionesId: String!) {
    marcar_como_leida(bandeja_notificaciones_id: $bandejaNotificacionesId)
}
