query HabitacionesToClean($hotel_id: ID!, $estado: estados_habitaciones!) {
    habitaciones(hotel_id: $hotel_id, estado: $estado) {
        habitacion_id
        numero_habitacion
        ultimos_datos {
            ultima_limpieza {
                fecha_inicio
            }
        }
        tipo_habitacion_id
        tipo_habitacion {
            nombre
            minutos_limpieza_retoque
            minutos_limpieza_detallada
            minutos_limpieza_normal
        }
    }
}

query HabitacionesToMaintenanceOrClean($hotel_id: ID!) {
    habitaciones(hotel_id: $hotel_id) {
        habitacion_id
        estado
        numero_habitacion
        colaborador_tareas_sin_finalizar {
            tarea_id
            colaborador_tarea_id
            fecha_termino
        }
        numero_habitacion
        ultimos_datos {
            ultima_limpieza {
                fecha_inicio
            }
        }
        tipo_habitacion_id
        tipo_habitacion {
            nombre
            minutos_limpieza_retoque
            minutos_limpieza_detallada
            minutos_limpieza_normal
        }
    }
}
