mutation Crear_reserva($crearReservaInput: CreateReservaInput!) {
    crear_reserva(crear_reserva_input: $crearReservaInput) {
        reserva {
            folio
        }
        ticket {
            ticket_id
        }
    }
}

mutation Actualizar_reserva($actualizarReservaInput: UpdateReservaInput!) {
    actualizar_reserva(actualizar_reserva_input: $actualizarReservaInput) {
        reserva {
            reserva_id
            folio
        }
    }
}

query GetTiposHabitacion($hotel_id: ID!) {
    tipo_habitaciones(hotel_id: $hotel_id) {
        nombre
        personas_incluidas
        tipo_habitacion_id
    }
}

query GetTiposTarifaReserva {
    tarifas {
        nombre
        tarifa_id
        costo_habitacion
        costo_persona_extra
    }
}

query GetServiciosResewrva {
    servicios {
        nombre
        servicio_id
    }
}

mutation AddPayReserva($pago: PayReservaInput!) {
    pagar_reserva(datos_reserva: $pago)
}

mutation AgregarPersonaExtraReserva($add_extras_reserva_input: AddExtrasReservaInput!) {
    agregar_extras_reserva(add_extras_reserva_input: $add_extras_reserva_input)
}

mutation AddComen($commentReserva: AddComentarioReservaInput!) {
    agregar_comentario_reserva(AddComentarioReservaInput: $commentReserva)
}
