query HistorialProduccionInventario($hotel_id: ID, $articulo_id: [ID!], $fecha_produccion: MonthSearchInput) {
    historial_producciones_inventarios(
        hotel_id: $hotel_id
        articulo_id: $articulo_id
        fecha_produccion: $fecha_produccion
    ) {
        historial_produccion_inventario_id
        articulo_id
        folio
        fecha_produccion
        cantidad_producida
        unidad
        costo_produccion
        costo_unidad_minima_produccion
        colaborador_id
        responsable {
            apellido_materno
            apellido_paterno
            nombre
            usuario_id
        }
    }
}

query KPISHistorialProduccion($hotel_id: ID, $articulo_id: ID!) {
    kpis_historial_producciones_inventarios(hotel_id: $hotel_id, articulo_id: $articulo_id) {
        articulo_id
        costo_total_inventario
        costo_unitario_promedio
        fecha_ultima_produccion
        produccion_receta
        unidades_inventario
        unidad
    }
}
