query getGastosCategorasPorMes($gastosCategoria: [String!]!, $hotel_id: ID!) {
  gastos_categoria_por_meses(month: $gastosCategoria, hotel_id: $hotel_id) {
    gastos_por_categoria{
      porcentaje
      total_gasto
      categoria {
        categoria
        presupuesto
        __typename
      }
      __typename
    }
    month
  }
}