mutation AjustarAsignacionPropina($ajustarAsignacionPropinaInput: AjustarAsignacionPropinaInput!) {
    ajustar_asignacion_propina(ajustarAsignacionPropinaInput: $ajustarAsignacionPropinaInput) {
        limite_disponible
        monto_recaudado
        propinas_ajustadas {
            asignacion_propina_id
            asignacion_propina {
                monto_ajuste: penalizacion
                remanente_por_ajuste
                ingreso_hotel
                fondo_original
            }
            colaborador {
                colaborador_id
                nombre
                apellido_materno
                apellido_paterno
                foto
                puesto {
                    puesto_id
                    nombre
                }
            }
            propina_por_ventas
            fondo_de_propinas
            comision_bancaria_sobre_fondo
            pago_correspondiente
        }
    }
}
