mutation UpdatePosicionMesa($updatePosicionMesaInput: UpdatePosicionMesaInput!) {
    actualizar_posicion_mesa(updatePosicionMesaRequest: $updatePosicionMesaInput) {
        mesa_id
        posicion {
            x
            y
            tamano
        }
    }
}
query getMesasConfig($hotel_id: ID!) {
    mesas(hotel_id: $hotel_id, eliminado: false) {
        mesa_id
        numero_mesa
    }
}
