mutation Login($loginInput: AuthLoginInput!) {
    login(loginInput: $loginInput) {
        token
    }
}

mutation LoginGoogle($loginGoogleInput: LoginGoogleInput!) {
    login_google(loginGoogleInput: $loginGoogleInput) {
        token
    }
}

mutation LoginHuella($template_sample: String!) {
    login_huella(FingerPrintLoginInput: { template_sample: $template_sample }) {
        token
    }
}

mutation Logout {
    logout
}

mutation SendChangePasswordViaEmail($sendChangePasswordViaEmailInput: sendChangePasswordViaEmailInput!) {
    sendChangePasswordViaEmail(sendChangePasswordViaEmailInput: $sendChangePasswordViaEmailInput)
}

mutation ChangePassword($changePasswordInput: ChangePasswordInput!) {
    changePassword(changePasswordInput: $changePasswordInput)
}
