query GetIncidencias($hotel_id: ID!, $fecha_operacion: DateSearchInput) {
    incidencias(hotel_id: $hotel_id, fecha_operacion: $fecha_operacion) {
        incidencia_id
        detalle
        habitacion_id
        folio
        fecha_registro
        fecha_cierre
        colaborador_id_reporta
        estado
        huesped
        matricula
        tipo_incidencia
        colaborador_reporta {
            nombre
            apellido_paterno
            apellido_materno
            puesto {
                nombre
            }
        }
        colaborador_id_cierra
        colaborador_cierra {
            nombre
            apellido_paterno
            apellido_materno
        }
        area
        severidad
        turno_id
        turno {
            nombre
        }
        habitacion {
            habitacion_id
            numero_habitacion
            tipo_habitacion_id
            tipo_habitacion {
                tipo_habitacion_id
                nombre
            }
        }
    }
}

query GetIncidenciaById($incidencia_id: ID!) {
    incidencias(incidencia_id: $incidencia_id) {
        incidencia_id
        detalle
        habitacion_id
        folio
        fecha_registro
        fecha_cierre
        colaborador_id_reporta
        estado
        huesped
        matricula
        vehiculo {
            color
            marca
            modelo
        }
        tipo_incidencia
        colaborador_reporta {
            nombre
            apellido_paterno
            apellido_materno
        }
        colaborador_id_cierra
        colaborador_cierra {
            nombre
            apellido_paterno
            apellido_materno
        }
        area
        severidad
        turno_id
        turno {
            nombre
        }
        habitacion {
            habitacion_id
            numero_habitacion
            tipo_habitacion_id
            tipo_habitacion {
                tipo_habitacion_id
                nombre
            }
        }
        comentario_cierre
    }
}

mutation ReabrirIncidencia($datos_incidencia: OpenIncidenciaInput!) {
    reabrir_incidencia(datos_incidencia: $datos_incidencia) {
        incidencia_id
    }
}

query GetIncidenciaByFilters($hotel_id: ID!, $matricula: String, $huesped: String) {
    incidencias(hotel_id: $hotel_id, matricula: $matricula, huesped: $huesped) {
        incidencia_id
        folio
        huesped
        matricula
    }
}
