query GetRestaurantColaboradores($datos_busqueda: SearchColaboradoresForTaskInput!) {
    colaboradores_disponibles_por_puesto(datos_busqueda: $datos_busqueda) {
        apellido_materno
        apellido_paterno
        nombre
        foto
        colaborador_id
        colaborador_in_hotel {
            puesto {
                puesto_id
                nombre
            }
        }
        en_turno
        ultima_tarea {
            fecha_inicio
            fecha_termino
            colaborador_tarea_id
        }
    }
}

query Usuario($usuario_id: ID!) {
    usuario(usuario_id: $usuario_id) {
        apellido_materno
        apellido_paterno
        nombre
    }
}
