mutation CancelarOrden($cancel_orden_input: CancelOrdenInput!) {
    cancelar_orden(cancel_orden_input: $cancel_orden_input) {
        ticket_id
        orden {
            colaborador_id
            comentario
            corte_id
            easyrewards_id
            estado_orden
            estado_pago
            fecha_cobro
            fecha_modificacion
            fecha_registro
            hotel_id
            monto_iva
            orden
            orden_id
            origen_orden
            pago_id
            panel_no_visible
            renta_id
            total_con_iva
            total_productos
            total_sin_iva
            turno_id
            usuario_id
        }
    }
}

mutation CancelarComanda($cancelar_comanda: CancelComandaInput!) {
    cancelar_comanda(CancelComandaInput: $cancelar_comanda) {
        ticket_id
    }
}

query getComandaCancelacion($comanda_id: ID!) {
    comanda(comanda_id: $comanda_id) {
        orden {
            orden
        }
        folio
        comanda_id
        detalles_orden {
            motivo_cancelacion
            fecha_cancelacion
            reembolso
            detalle_orden_id
            comentarios
            almacen_articulo_id
            cantidad
            costo_con_iva
            monto_iva
            almacen_articulo {
                precio
                articulo_id
                categoria_id
                articulo {
                    articulo_id
                    nombre
                    contenido
                    unidad
                    descripcion
                    precio {
                        monto
                    }
                    tipo
                    extra
                    categoria_id
                    categoria_articulo {
                        nombre
                    }
                }
            }
            extras {
                extra_detalle_orden_id
                detalle_orden_id
                almacen_articulo_id
                costo_con_iva
                monto_iva
                cantidad
                almacen_articulo {
                    almacen_articulo_id
                    articulo_id
                    articulo {
                        nombre
                        contenido
                        unidad
                        descripcion
                        categoria_id
                        tipo
                        extra
                        categoria_articulo {
                            nombre
                        }
                        precio {
                            monto
                        }
                    }
                }
            }
        }
    }
}

query CancelacionOrdenes($orden_id: [ID!]!, $hotel_id: ID, $fecha_registro: DateSearchInput) {
    ordenes(orden_id: $orden_id, hotel_id: $hotel_id, fecha_registro: $fecha_registro) {
        orden
        orden_id
        estado_pago
        estado_orden
        origen_orden
        fecha_registro
        fecha_modificacion
        total_con_iva
        total_sin_iva
        colaborador_id
        renta_id
        turno_id
        turno {
            nombre
        }
        colaborador_entrega {
            nombre
            apellido_materno
            apellido_paterno
        }
        renta {
            habitacion_id
            habitacion {
                numero_habitacion
                tipo_habitacion_id
                tipo_habitacion {
                    nombre
                }
            }
        }
        detalles_orden {
            motivo_cancelacion
            fecha_cancelacion
            reembolso
            detalle_orden_id
            comentarios
            almacen_articulo_id
            cantidad
            costo_con_iva
            monto_iva
            almacen_articulo {
                precio
                articulo_id
                articulo {
                    articulo_id
                    nombre
                    contenido
                    unidad
                    descripcion
                    precio {
                        monto
                    }
                    tipo
                    extra
                    categoria_id
                    categoria_articulo {
                        nombre
                    }
                }
            }
            extras {
                extra_detalle_orden_id
                detalle_orden_id
                almacen_articulo_id
                costo_con_iva
                monto_iva
                cantidad
                almacen_articulo {
                    almacen_articulo_id
                    articulo_id
                    articulo {
                        nombre
                        contenido
                        unidad
                        descripcion
                        categoria_id
                        tipo
                        extra
                        categoria_articulo {
                            nombre
                        }
                        precio {
                            monto
                        }
                    }
                }
            }
        }
        easyrewards_id
        pago_id
        pago {
            pago_id
            fecha_pago
            total
            ticket_id
            detalles_pago {
                detalle_pago_id
                pago_id
                ultimos_digitos
                subtotal
                tipo_pago
                numero_referencia
                easyrewards_id
            }
        }
        propina {
            total
            propina_id
            detalles_pago {
                ultimos_digitos
                tipo_pago
                subtotal
            }
        }
        mesa {
            numero_mesa
        }
    }
}
