query GetColaboradoresForPropinaDrop($hotel_id: ID) {
    hotel_colaboradores(hotel_id: $hotel_id, eliminado: false) {
        colaborador_id
        colaborador {
            colaborador_id
            nombre
            apellido_paterno
            apellido_materno
            area {
                area_id
                nombre
            }
        }
    }
}
