mutation CrearMesaAsignada($input: CreateMesaAsignadaInput!) {
    crear_mesa_asignada(CreateMesaAsignadaInput: $input) {
        mesa_id
    }
}

query GetRestaurantAreaColaboradores($hotel_id: ID, $area_id: ID) {
    colaboradores(en_turno: true, eliminado: false, hotel_id: $hotel_id, area_id: $area_id) {
        colaborador_id
        nombre
        apellido_materno
        apellido_paterno
        foto
    }
}

query GetAreaRestaurante($nombre: String, $hotel_id: ID) {
    areas(hotel_id: $hotel_id, nombre: $nombre, eliminado: false) {
        area_id
    }
}
