query getFajillas {
        fajillas {
            monto
            estatus
            fajilla_id
            fecha_creacion
            fecha_autorizaicion
            usuario_autorizo {
              nombre
              apellido_materno
              apellido_paterno
            }
            usuario_creo_id
            usuario_creo {
              nombre
              apellido_paterno
              apellido_materno
            }
            usuario_autorizo_id
            turno_id
            comentario
            folio
        }
    }