mutation EditarMetodoDePagoMovimiento($editMetodoPagoTicketInput: EditMetodoPagoTicketInput!) {
    editar_metodo_pago(editMetodoPagoTicketInput: $editMetodoPagoTicketInput) {
        ticket_id
    }
}
