query getEasyrewards($easyrewards_id: String!) {
    obten_saldo(easyrewards_id: $easyrewards_id) {
        saldo
    }
}

mutation AbonarSaldoEasyrewards(
    $easyrewards_id: String!
    $folio_ticket: String!
    $hotel_id: ID!
    $monto_alimentos: Float!
    $monto_bebidas: Float!
    $monto_extras: Float!
    $monto_habitacion: Float!
    $monto_sexspa: Float!
    $origen: Float!
) {
    acumula_puntos(
        AcumulaPuntosInput: {
            data: {
                folio_ticket: $folio_ticket
                monto_alimentos: $monto_alimentos
                monto_bebidas: $monto_bebidas
                monto_extras: $monto_extras
                monto_habitacion: $monto_habitacion
                monto_sexspa: $monto_sexspa
                origen: $origen
            }
            easyrewards_id: $easyrewards_id
            hotel_id: $hotel_id
        }
    ) {
        saldo
    }
}

mutation DescontarSaldoEasyrewards(
    $easyrewards_id: String!
    $folio_ticket: String!
    $hotel_id: ID!
    $puntos_descontar: Float!
) {
    descuenta_puntos(
        DescuentaPuntosInput: {
            easyrewards_id: $easyrewards_id
            folio_ticket: $folio_ticket
            hotel_id: $hotel_id
            puntos_descontar: $puntos_descontar
        }
    ) {
        saldo
    }
}
