query GetReservacionesTable($id: [ID!]!, $hotel_id: ID!, $fecha_entrada: DateSearchInput) {
    reservas(reserva_id: $id, hotel_id: $hotel_id, fecha_entrada: $fecha_entrada) {
        reserva_id
        codigo_ota
        corte_id
        folio
        estado
        fecha_cancelacion
        fecha_registro
        fecha_salida
        motivo_cancelacion
        fecha_entrada
        personas_extras
        origen
        tipo_habitacion_id
        tipo_de_habitacion {
            nombre
        }
        habitacion_id
        habitacion {
            numero_habitacion
            habitacion_id
            tipo_habitacion {
                nombre
            }
        }
        tarifa_id
        tarifa {
            nombre
            personas_extra_max
            costo_persona_extra
            costo_habitacion
            hora_checkin
            hora_checkout
        }
        correo_huesped
        nombre_huesped
        telefono_huesped
        numero_personas
        usuario {
            nombre
        }
        estado_pago
        total
        pagos {
            pago_id
            total
            fecha_pago
            detalles_pago {
                detalle_pago_id
                subtotal
                tipo_pago
                ultimos_digitos
                numero_referencia
                easyrewards_id
            }
            extras {
                monto_devuelto_cancelacion
                fecha_cancelacion
                fecha_pago
                fecha_solicitud
                monto_extra
                motivo_cancelacion
                numero
                tipo_extra
            }
        }
        experiencias_reserva {
            experiencia_reserva_id
            experiencia_id
            total
            estado
            experiencia {
                nombre
            }
        }
        comentarios {
            comentario
            fecha
        }
    }
}
query GetHabitacionTable($idHabitacin: ID!) {
    habitacion(habitacion_id: $idHabitacin) {
        numero_habitacion
        tipo_habitacion {
            nombre
        }
    }
}

query GetClienteResTable($idCliente: ID!) {
    cliente(cliente_id: $idCliente) {
        nombre
    }
}
