query Hotel_colaboradores($hotel_id: ID) {
    colaboradores(hotel_id: $hotel_id, eliminado: false, en_turno: true) {
        colaborador_id
        nombre
        usuario_id
        apellido_paterno
        turno_id
        foto
        en_turno
        colaborador_id
        ultima_tarea {
            fecha_inicio
            fecha_termino
        }
        mesa_asignada_activa {
            has_mesa_activa
        }
        puesto {
            nombre
        }
    }
}
