query getHabitaciones($hotelIdFilter: ID!) {
    habitaciones(hotel_id: $hotelIdFilter) {
        estado
        habitacion_id
        numero_habitacion
        ultima_renta {
            renta_id
            fecha_condensada
        }
    }
}
