query Rentas($renta_id: [ID!]!, $fecha_registro: DateSearchInput, $fecha_salida: DateSearchInput, $hotel_id: ID!) {
    rentas(renta_id: $renta_id, fecha_registro: $fecha_registro, fecha_salida: $fecha_salida, hotel_id: $hotel_id) {
        renta_id
        fecha_registro
        numero_personas
        personas_extra
        tipo_entrada
        reserva_id
        habitacion_id
        habitacion {
            hotel_id
        }
        extras {
            monto_extra
            tipo_extra
            fecha_pago
        }
    }
}
