query HabitacionesConfig ($hotel_id: ID!) {
  habitaciones(hotel_id: $hotel_id) {
    habitacion_id
    numero_habitacion
    tipo_habitacion_id
    tipo_habitacion {
      nombre
    }
  }
}

mutation UpdatePosicionHabitacion($updatePosicionHabitacionInput: UpdatePosicionHabitacionInput!) {
  actualizar_posicion_habitacion(updatePosicionHabitacionRequest: $updatePosicionHabitacionInput) {
    habitacion_id
    posicion {
      x
      y
      tamano
    }
  }
}

mutation ActualizarHotelMinimal($datos_hotel: UpdateHotelInput!) {
  actualizar_hotel(datos_hotel: $datos_hotel) {
    hotel_id
    nombre_hotel
    configurations {
      cardHabitacion {
        tamano_fijo
        tamano
      }
    }
  }
}