 mutation CerrarCuentaMesaAsignada(
        $cerrarCuentaMesaAsignadaInput: CloseBillMesaAsignadaInput!
    ) {
        cerrar_cuenta_mesa_asignada(
            cerrarCuentaMesaAsignadaInput: $cerrarCuentaMesaAsignadaInput
        ) {
            mesa_asignada_id
            mesa_id
            orden_id
            fecha_cuenta_cerrada
            fecha_registro
            fecha_salida
            colaborador_asignado_id
            colaborador_atendio {
                nombre
                apellido_paterno
                apellido_materno
            }
        }
    }