query searchArticuloForReport($hotel_id: ID, $pagination_options: PageOptionsArgs!, $nameFilter: String) {
    almacenes_articulos(
        hotel_id: $hotel_id
        eliminado: false
        nombre_articulo_filters: {
          like: $nameFilter,
          order: ASC
        }
        filter_estado_articulo: activado
        filter_tipo_articulo: [venta, receta, insumo, proceso]
        filter_duplicados: true
        pagination_options: $pagination_options
    ) {
      paginacion{
        pagina_actual
        total_paginas
      }
      almacenes_articulos {
            articulo_id
            articulo {
                nombre
            }
        }
    }
}