query SearchArticulos($hotel_id: ID!) {
    articulos(hotel_id: $hotel_id, insumo: false, eliminado: false) {
        articulo_id
        categoria_id
        foto
        precio(hotel_id: $hotel_id) {
            monto
        }
        nombre
        marca
        contenido
        unidad
        descripcion
    }
}
