query GetCortesAgrupados(
    $hotel_id: ID!
    $unidad_tiempo: UnidadTiempoFiltro!
    $fecha_inicio_corte: DateSearchInput
    $fecha_fin_corte: DateSearchInput
    $fecha_cierre_corte: DateSearchInput
) {
    cortes_agrupados(
        hotel_id: $hotel_id
        unidad_tiempo: $unidad_tiempo
        fecha_inicio_corte: $fecha_inicio_corte
        fecha_fin_corte: $fecha_fin_corte
        fecha_cierre_corte: $fecha_cierre_corte
    ) {
        cortes {
            corte_id
            turno_id
            folio
            turno {
                nombre
            }
            fecha_inicio_corte
            fecha_fin_corte
            fecha_cierre_corte
            __typename
        }
        fecha
        total_corte
    }
}
