mutation EditarDatosVehiculo($editVehiculoInput: EditVehiculoDataInput!) {
    editar_datos_vehiculo(EditVehiculoDataInput: $editVehiculoInput) {
        matricula
        color
        marca
        modelo
    }
}
