export const REACT_APP_GQL_API = process.env.REACT_APP_GQL_API
export const REACT_APP_GQL_API_WS = process.env.REACT_APP_GQL_API_WS
export const REACT_APP_GOOGLE_OAUTH_API_CLIENT_ID = process.env.REACT_APP_GOOGLE_OAUTH_API_CLIENT_ID
export const REACT_APP_ACCES_KEY = process.env.REACT_APP_ACCES_KEY
export const REACT_APP_SECRET_KEY = process.env.REACT_APP_SECRET_KEY
export const REACT_APP_BUCKET_REGION = process.env.REACT_APP_BUCKET_REGION
export const REACT_APP_SPACES_ENDPOINT = process.env.REACT_APP_SPACES_ENDPOINT
export const REACT_APP_ARTICULOS_BUCKET = process.env.REACT_APP_ARTICULOS_BUCKET
export const REACT_APP_AVATARS_BUCKET_FOLDER = process.env.REACT_APP_AVATARS_BUCKET_FOLDER

export const REACT_APP_REST_API = process.env.REACT_APP_REST_API
