query Tarifas($tipo_habitacion_id: ID!, $hotel_id: ID!) {
    tarifas(tipo_habitacion_id: $tipo_habitacion_id, hotel_id: $hotel_id, eliminado: false) {
        tarifa_id
        nombre
        eliminado
        estatus
        duracion_renta
        costo_habitacion
        costo_persona_extra
        costo_early_checkin
        costo_hospedaje_extra
        costo_hora_extra
        personas_extra_max
        tipo_habitacion_id
        horas_extra_max
        hora_checkin
        hora_checkout
        tipo_alojamiento
        tipo_tarifa
        fecha_final
        fecha_inicio
        hora_final
        hora_inicio
        dias_disponibles
    }
}
