query SearchRecipesProcess($hotel_id: ID!, $nameFilter: String!, $pagination_options: PageOptionsArgs!) {
    almacenes_articulos(
        hotel_id: $hotel_id
        filter_tipo_articulo: [receta, proceso]
        eliminado: false
        nombre_articulo_filters: { like: $nameFilter }
        pagination_options: $pagination_options
    ) {
        paginacion {
            pagina_actual
            total_paginas
            total_registros
        }
        almacenes_articulos {
            almacen_id
            almacen_articulo_id
            articulo_id
            ultima_preparacion
            cantidad
            precio
            costo
            articulo {
                nombre
                foto
                categoria_id
                contenido
                stock
                descripcion
                categoria_articulo {
                    nombre
                }
                costo {
                    monto
                }
                precio(hotel_id: $hotel_id) {
                    monto
                }
                folio
                tipo
                unidad
                estado
                extra
            }
        }
    }
}
