query GetOrdenForUpdate($orden_id: ID!) {
    orden(orden_id: $orden_id) {
        orden
        estado_orden
        orden_id
        detalles_orden(estado: [en_preparacion, por_entregar, en_entrega]) {
            detalle_orden_id
            comanda_id
            orden_id
            cantidad
            estado
            costo_con_iva
            costo_sin_iva
            monto_iva
            comentarios
            almacen_articulo_id
            almacen_articulo {
                almacen_articulo_id
                precio
                articulo_id
                articulo {
                    articulo_id
                    nombre
                    contenido
                    unidad
                    descripcion
                    precio {
                        monto
                    }
                    tipo
                    extra
                    categoria_id
                    categoria_articulo {
                        nombre
                    }
                }
            }
            extras {
                extra_detalle_orden_id
                detalle_orden_id
                almacen_articulo_id
                costo_con_iva
                costo_sin_iva
                monto_iva
                cantidad
                almacen_articulo {
                    almacen_articulo_id
                    articulo_id
                    articulo {
                        nombre
                        contenido
                        unidad
                        descripcion
                        categoria_id
                        tipo
                        extra
                        categoria_articulo {
                            nombre
                        }
                        precio {
                            monto
                        }
                    }
                }
            }
        }
    }
}

mutation EditarOrden($input: EditOrdenInput!) {
    editar_orden(EditOrdenInput: $input) {
        orden_id
    }
}
