query GetTurnosAtencion($hotel_id: ID!, $estado: [EstadosTurnosAtencion!]) {
    turnos_atencion(hotel_id: $hotel_id, estado: $estado) {
        turno_atencion_id
        usuario_id
        fecha_registro
        folio
        nombre_o_matricula
        folio_turno
        tipo_habitacion_id
        tipo_habitacion {
            tipo_habitacion_id
            nombre
        }
        colaborador {
            nombre
        }
    }
}

mutation CrearTurnoAtencion($input: CreateTurnoAtencionInput!) {
    crear_turno_atencion(crear_turno_atencion_input: $input) {
        turno_atencion_id
        folio_turno
    }
}

mutation EliminarTurnoAtencion($input: DeleteTurnoAtencionInput!) {
    eliminar_turno_atencion(eliminar_turno_atencion_input: $input)
}

mutation ActualizarTurnoAtencion($input: UpdateTurnoAtencionInput!) {
    actualizar_turno_atencion(actualizar_turno_atencion_input: $input) {
        turno_atencion_id
        folio_turno
        estado
    }
}
