query GetComentariosColaborador($colaborador_tarea_id: ID!) {
    colaborador_tarea(colaborador_tarea_id: $colaborador_tarea_id) {
        colaborador_tarea_id
        comentarios {
            comentario
            fecha
        }
    }
}

mutation AgregarComentarioATarea($comentarios: AddCommentToTaskInput!) {
    agregar_comentarios_a_tarea(comentarios: $comentarios) {
        comentarios {
            comentario
            fecha
        }
    }
}
