subscription ListenCheckDisponibilidadHabitaciones {
    checkDisponibilidadHabitaciones {
        disponibilidad_habitaciones {
            accion
        }
        lista_de_espera {
            turno_en_curso {
                turno_atencion_id
                folio
            }
            lista {
                tipo_habitacion_id
                nombre
                turnos_atencion(estado: [en_espera, en_curso]) {
                    folio
                    estado
                }
            }
        }
    }
}
