query GetDisponibilidadHabitaciones($hotel_id: ID!) {
    disponibilidad_habitaciones(hotel_id: $hotel_id) {
        tipo_habitacion_id
        nombre
        foto
        personas_incluidas
        disponibles
    }
}

query GetDisponibilidadTarifas($hotel_id: ID) {
    tarifas(hotel_id: $hotel_id, eliminado: false, pantalla_disponibilidad: true) {
        nombre
        tarifa_id
        dias_disponibles
        tipo_habitacion_id
        tipo_tarifa
        costo_habitacion
        costo_persona_extra
        costo_reserva
        duracion_renta
        personas_extra_max
        costo_reserva
        tipo_tarifa
        pantalla_disponibilidad
    }
}

query GetDisponibilidadTurnosAtencion($hotel_id: ID!, $estado: [EstadosTurnosAtencion!]) {
    turnos_atencion(hotel_id: $hotel_id, estado: $estado) {
        tipo_habitacion_id
        tipo_habitacion {
            nombre
        }
        folio
        folio_turno
        estado
    }
}
