query GetCortesHistorial($fecha_inicio_corte: DateSearchInput, $hotel_id: ID, $estatus: EstatusCorte) {
        cortes(fecha_inicio_corte: $fecha_inicio_corte, hotel_id: $hotel_id, estatus: $estatus) {
            corte_id
            folio
            total_corte
            turno_id
            turno {
                nombre
            }
        }
    }