query Historial_movimientos_inventario(
  $fecha_registro: MonthSearchInput,
  $hotel_id: ID!,
  $pagination_options: PageOptionsArgs!,
  $nombre_articulo: String,
  $tipo_articulo: TipoArticulo,
  $movimiento: MovimientoHistorialInventario,
  $tipo: TipoMovimientoHistorialInventario
) {
  historial_movimientos_inventario(
    fecha_registro: $fecha_registro
    hotel_id: $hotel_id
    pagination_options: $pagination_options
    nombre_articulo: $nombre_articulo
    tipo_articulo: $tipo_articulo
    movimiento: $movimiento
    tipo: $tipo
  ) {
        paginacion {
            pagina_actual
            total_paginas
        }
        historial_movimientos_inventario {
            historial_movimiento_inventario_id
            articulo_id
            cantidad
            costo_actual
            fecha_registro
            folio
            hotel_id
            movimiento
            nombre_articulo
            precio
            salida_id
            surtido_id
            tipo
            almacen_articulo_id
            articulo {
                unidad
                folio
                tipo
            }
            origen_destino
            responsable {
                nombre
                apellido_paterno
                apellido_materno
            }
        }
    }
}

query Surtido($surtido_id: ID!) {
    surtido(surtido_id: $surtido_id) {
        almacen {
            almacen_id
        }
        articulo {
            articulo_id
        }
        cantidad
        colaborador_id
        costo_total
        costo_unitario
        fecha_ingreso
        hotel_id
        surtido_id
    }
}

query Colaborador($colaborador_id: ID!) {
    colaborador(colaborador_id: $colaborador_id) {
        apellido_materno
        apellido_paterno
        nombre
    }
}

query Salida_inventario($salida_id: ID!) {
    salida_inventario(salida_id: $salida_id) {
        almacen_articulo_id
        articulo {
            articulo_id
        }
        cantidad
        colaborador_id
        comentario
        fecha_salida
        hotel_id
        motivo
        salida_id
    }
}

query Informe_inventario($hotel_id: ID!, $almacen_id: ID) {
    informe_inventario(hotel_id: $hotel_id, almacen_id: $almacen_id) {
        cantidad_articulos
        costo_total_inventario
        articulos_agotados
        articulos_por_agotarse
        valor_comercial
    }
}

query Informe_historial_movimientos_inventario($hotel_id: ID!, $fecha_registro: DateSearchInput) {
    informe_historial_movimientos_inventario(hotel_id: $hotel_id, fecha_registro: $fecha_registro) {
        salidas_venta {
            total
            unidades
        }
        salidas_insumos {
            total
            unidades
        }
        merma {
            total
            unidades
        }
        entradas_productos {
            total
            unidades
        }
        entradas_insumos {
            total
            unidades
        }
    }
}
