query GetPerfil {
    mi_perfil {
        usuario_id
        nombre
        apellido_paterno
        apellido_materno
        correo
        fecha_registro
        fecha_modificacion
        eliminado
        telefono
        estatus
        hotel {
            nombre_hotel
            hotel_id
            zona_horaria
            logo_hotel
        }
        roles {
            rol_id
            grupo_hotel_id
            nombre
            eliminado
            grupo_hotel {
                grupo_hotel_id
            }
        }
        turno {
            nombre
            turno_id
        }
        colaborador {
            colaborador_id
            foto
        }
    }
}

mutation UpdatePerfilColaborador($input: UpdateColaboradorInput!) {
    editar_colaborador(datos_colaborador: $input) {
        colaborador_id
        foto
    }
}
