query Articulos($fecha_registro: DateSearchInput, $pagination_options: PageOptionsArgs!) {
    almacenes_articulos (pagination_options: $pagination_options) {
        almacenes_articulos {
          articulo_id
        articulo {
          cantidad_minima
          cantidad_vendida(fecha_registro: $fecha_registro)
          categoria_id
          contenido
          costo {
            monto
          }
          descripcion
          eliminado
          estado
          fecha_eliminado
          fecha_registro
          folio
          foto
          tipo
          marca
          nombre
          precio {
            monto
          }
          stock
          unidad
        }
        }
    }
}