subscription ListenCheckMesas {
    checkMesas {
        hotel_id
        mesa_id
        numero_mesa
        cantidad_personas
        posicion {
          x
          y
        }
        eliminado
        estado
        motivo_bloqueo
        fecha_modificacion
        usuario_modifico_id
        ultima_asignacion {
            fecha_salida
            colaborador_asignado_id
            colaborador_atendio {
                nombre
                apellido_paterno
                apellido_materno
            }
        }
        asignacion_actual {
            colaborador_asignado_id
            fecha_registro
            fecha_cuenta_cerrada
            mesa_asignada_id
            mesa_id
            orden_id
            colaborador_atendio {
                nombre
                apellido_paterno
                apellido_materno
            }
        }
        estado_dinamico {
            estado_activo
            comanda_activa {
                comanda_id
                estado_comanda
                fecha_modificacion
                fecha_registro
                folio
                orden_id
                total_comanda
                usuario_id
            }
        }
    }
}
