query GetSurtidosByAlmacenArtId($almacen_articulo_id: ID, $fecha_ingreso: DateSearchInput) {
    surtidos(almacen_articulo_id: $almacen_articulo_id, fecha_ingreso: $fecha_ingreso) {
        surtido_id
        almacen_articulo_id
        cantidad
        colaborador_id
        costo_total
        costo_unitario
        fecha_ingreso
        folio
        numero_orden_factura
        tipo
        colaborador {
            nombre
            apellido_paterno
            apellido_materno
        }
    }
}

query GetAlmacenArticuloForSurtido($almacen_articulo_id: ID!, $hotel_id: ID!) {
    almacen_articulo(almacen_articulo_id: $almacen_articulo_id) {
        almacen_articulo_id
        almacen_id
        articulo_id
        cantidad
        almacen {
            almacen_id
            nombre
        }
        articulo {
            articulo_id
            marca
            nombre
            precio(hotel_id: $hotel_id) {
                monto
            }
            costo {
                monto
            }
            cantidad_minima
            stock
        }
        ultimo_surtido {
            fecha_ingreso
        }
    }
}
