query getOrdenEdit($input: ID!) {
  orden(orden_id: $input) {
    orden_id
    orden
    detalles_orden {
      costo_con_iva
      costo_sin_iva
      comanda_id
      comentarios
      detalle_orden_id
      cantidad
      comentarios
      extras {
        extra_detalle_orden_id
        cantidad
        almacen_articulo_id
        almacen_articulo {
          articulo {
            nombre
            costo {
              monto
            }
            precio {
              monto
            }
            categoria_id
            categoria_articulo {
              nombre
            }
          }
        }
      }
      almacen_articulo_id
      almacen_articulo {
        almacen_articulo_id
        articulo_id
        articulo {
          costo {
            monto
          }
          articulo_id
          nombre
          precio {
            monto
          }
          categoria_id
          categoria_articulo {
            categoria_id
            nombre
          }
        }
      }
    }
  }
}