query Transacciones_renta($renta_id: ID!) {
    transacciones_renta(renta_id: $renta_id) {
        renta {
            estado
            folio
            early_checkin
            es_renta_cancelable
            montos_cancelacion {
                total
                parcial
            }
            habitacion {
                tipo_habitacion {
                    nombre
                }
            }
            renta_id
            corte_id
            ticket_id
            tarifa {
                nombre
            }
            tipo_alojamiento
            total
        }
        transacciones_checkin {
            extras {
                extra_id
                corte_id
                tipo_extra
                numero
                monto_extra
            }
            ticket {
                ticket_id
                folio
                fecha_impresion
            }
        }
        transacciones {
            ticket {
                ticket_id
                folio
                fecha_impresion
            }
            extras {
                extra_id
                corte_id
                tipo_extra
                numero
                monto_extra
                total_con_propina
            }
        }
        ordenes {
            ticket_id
            orden_id
            orden {
                orden
                orden_id
                corte_id
                total_con_iva
                fecha_registro
                detalles_orden {
                    detalle_orden_id
                    cantidad
                    almacen_articulo_id
                    almacen_articulo {
                        almacen_articulo_id
                        articulo_id
                        articulo {
                            articulo_id
                            nombre
                            categoria_id
                            categoria_articulo {
                                categoria_id
                                nombre
                            }
                        }
                    }
                    extras {
                        extra_detalle_orden_id
                        cantidad
                        almacen_articulo_id
                        almacen_articulo {
                            almacen_articulo_id
                            articulo_id
                            articulo {
                                articulo_id
                                nombre
                                categoria_id
                                categoria_articulo {
                                    categoria_id
                                    nombre
                                }
                            }
                        }
                    }
                }
            }
            ticket {
                ticket_id
                folio
            }
        }
    }
}
